version: "3.8"

services:
  app:
      build:
        context: .
      container_name: shorten_api
      command: iex -S mix phx.server
      restart: unless-stopped
      ports:
        - "4000:4000"
      volumes:
        - .:/shorten_api
      env_file:
        - .env
      depends_on:
        - db

  db:
      image: postgres:11.7
      container_name: shorten_db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=shorten_api_dev
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      logging:
        driver: json-file
        options:
          max-size: "50m"
          max-file: "10"

volumes:
  postgres_data: 